### ISSUE TITLE
scaling of foot ligaments

### ISSUE THREAD

**Issue by VDB-Bram** [KULeuvenNeuromechanics/PredSim#120]
**Is your feature request related to a problem? Please describe.**

Currenlty there is no code to easily scale the properties of ligaments present in the foot.

**Describe the solution you'd like**

Added boolean to [AdaptOpenSimModel
](https://github.com/KULeuvenNeuromechanics/PredSim/blob/master/AdaptOpenSimModel/AdaptOpenSimModel.m) and function to scale the ligaments based on body mass (pcsa) and length (resting length).

**Describe alternatives you've considered**

Programmatically calculating the new values and maually adding them to the model.

**Additional context**

/

**Are you willing to contribute in the development of this feature?**

Yes.

**Comment by VDB-Bram** [comment]
Input needed on how to do the length scaling: what ratio should we use? Keeping in mind that, ideally, it should be possible to get the values through the OpenSim API.

**Comment by Lars-DHondt-KUL** [comment]
OpenSim scale tool does scale the resting length (tested with OpenSim 4.5 beta)

I added a function to the linked branch that scales the ligament property pcsa_force proportional to mass^(2/3)
