### ISSUE TITLE
Missing geometry in Model DHondt_2023_3seg

### ISSUE THREAD

**Issue by linghuix** [KULeuvenNeuromechanics/PredSim#148]
**Describe the bug**

Some stl files for the foot segment are missing.

**Log file**

Loaded model 3-segment_foot_model_fixed_knee_axis from file C:/Users/lingh/OneDrive - KTH/ExMaterials/7-Doctor/Research/2-simulation/Subjects/DHondt_2023_3seg/DHondt_2023_3seg_cal.osim
Couldn't find file 'model_r_talus.stl'.
Couldn't find file 'model_r_calcaneus_2.stl'.
Couldn't find file 'model_r_midfoot.stl'.
Couldn't find file 'model_r_forefoot.stl'.
Couldn't find file 'model_r_toes.stl'.
Couldn't find file 'model_l_talus.stl'.
Couldn't find file 'model_l_calcaneus_2.stl'.
Couldn't find file 'model_l_midfoot.stl'.
Couldn't find file 'model_l_forefoot.stl'.
Couldn't find file 'model_l_toes.stl'.

**Software versions**
 - Windows 11
 - OpenSim 4.4...

I am wondering if it will affect the simulation results or it is just visualisation?

**Comment by VDB-Bram** [comment]
This does not affect the simulation results; the .stl files are only there for visualisation.

**Comment by VDB-Bram** [comment]
See https://github.com/Lars-DHondt-KUL/3dpredictsim/tree/extended_foot_model/OpenSimModel/Nominal%20models for info on the geometry files and where to get them.
