### ISSUE TITLE
Information: "how to select an initial guess?"

### ISSUE THREAD

**Issue by Lars-DHondt-KUL** [KULeuvenNeuromechanics/PredSim#152]
Add a short write-up of good practices and tips&tricks to selecting/creating an initial guess.

Where should we put this? Maybe on forum so people can discuss this?

**Comment by VDB-Bram** [comment]
Adding this to the forum is a good idea.

**Comment by VDB-Bram** [comment]
Started a discussion on this topic.

See https://github.com/KULeuvenNeuromechanics/PredSim/discussions/170
