### ISSUE TITLE
cmake cache

### ISSUE THREAD

**Issue by MaartenAfschrift** [KULeuvenNeuromechanics/PredSim#36]
problem with cmake cache: currently impossible to change cmake compiler after first run (due to cmacke cache ?)
(this is a problem in opensimAD submodule)

**Comment by Lars-DHondt-KUL** [comment]
Would this part not take care of that?

```
% remove specific folders from buildExpressionGraph, build-ExternalFunction
% and install-ExternalFunction
rmdir(path_external_functions_filename_build,'s');
rmdir(path_external_functions_filename_install,'s');
pathBuildExpressionGraph = fullfile(pathMain, 'buildExpressionGraph');
pathBuild = fullfile(pathBuildExpressionGraph,filename);
rmdir(pathBuild ,'s');
```
https://github.com/KULeuvenNeuromechanics/PredSim/blob/master/PreProcessing/CreateDllFromFoo_Jac.m#L70
