### ISSUE TITLE
Default IG for full gait cycle is lacking

### ISSUE THREAD

**Issue by VDB-Bram** [KULeuvenNeuromechanics/PredSim#43]
Currently there is no default IG mot-file provided for simulating a full gait cycle. Full gait cycle simulations do work if you use the default guess of half a gait cycle and put S.subject.IG_selection_gaitCyclePercent at 100. But, it might be better for the convergence to have an actual full gait cycle as IG?

https://github.com/KULeuvenNeuromechanics/PredSim/blob/51bb020cb972d6fed7e83505892796cdb716004f/main.m#L33

**Comment by Lars-DHondt-KUL** [comment]
fixed #59

**Comment by Lars-DHondt-KUL** [comment]
I don't expect that to matter too much
