### ISSUE TITLE
min distance bounds

### ISSUE THREAD

**Issue by dgupta7** [KULeuvenNeuromechanics/PredSim#52]
Currently the min distance between segments like hand-femur, the two toes, etc are a setting. These min distance should change based on body type. These are often not thought about by the user. This can be a big issue, specially with simulations of kids.
We can make a height based scaling of these bounds, and add things in readme, or warning to tell the user to make sure these are further adjusted based on the participant.

**Comment by VDB-Bram** [comment]
could/should this be added to #89?

**Comment by Lars-DHondt-KUL** [comment]
Defining min distance bounds was changed in #107 , so should be fine now.
