### ISSUE TITLE
Creating external function is not thread-safe

### ISSUE THREAD

**Issue by Lars-DHondt-KUL** [KULeuvenNeuromechanics/PredSim#53]
When running multiple simulation as batch jobs, it can happen that 2 simulations are generating an external function at the same time. This results in an issue where both are trying to read/write to the same temporary files (e.g. foo.py)

How to avoid issue: wait until 1st job is done generating external function before starting next one. Queued simulations might still end up generating simultaneously.

Proposed solution: do not use `foo`, but a filename related to the savename or job id.

**Comment by Lars-DHondt-KUL** [comment]
You can use https://github.com/KULeuvenNeuromechanics/PredSim/blob/master/Tests/compare_external_functions.m if you suspect that 2 results from your batch (that were run as job k and job k+1) look suspiciously familiar

**Comment by VDB-Bram** [comment]
Is it possible that external functions are still different but the functions themselves are from the wrong osim model? E.g. you run 4 simulations in parallel, can it be that simulation k+1 used the foo.m of simulation k, simulation k+2 the foo.m from k+1 etc.?

**Comment by Lars-DHondt-KUL** [comment]
I think the issue occurs when job k+1 overwrites the foo.py generated by job k, before k started reading its foo.py. 
This could technically cascade, but would require very specific timings.

Only jobs that started withing 2 minutes from each other can be mixed up, as far as I'm aware.

Note that we're working on an overhaul of the code that creates the external function, so this issue will be addressed then.
