### ISSUE TITLE
bug with getHeelstrikeSimulation when doing FullGaitCycle simulation

### ISSUE THREAD

**Issue by VDB-Bram** [KULeuvenNeuromechanics/PredSim#72]
*Before submitting a bug report, read the error messages in MATLAB. Some errors are there to inform you about inconsistent inputs for certain settings.* 

**Describe the bug**
I ran a FullGaitCycle (FGC) simulation with the model of a child. HalfGaitCycle PredSims went fine, when doing FGC it finds an optimal solution, but the results are not retrieved.

Inspecting the error of the job, it seems that the input argument `threshold_init` is missing in https://github.com/KULeuvenNeuromechanics/PredSim/blob/14c094e48a60839f50d504e558e6437c1a6cdd8e/OCP/OCP_formulation.m#L1120

**To Reproduce**
1. Fork of PredSim main; ran as a job
2. genric settings, with exception of: S.subject.IG_pelvis_y = 1 and S.misc.gaitmotion_type = 'FullGaitCycle'
4. Gen scaled opensim model of a child, similar to hamner_modified (approx as tall as adult, but weighing less)

**Log file**
[CP15_job254_log.txt](https://github.com/KULeuvenNeuromechanics/PredSim/files/10868480/CP15_job254_log.txt)

other error code
````
job254 = 

 Job

    Properties: 

                   ID: 254
                 Type: independent
             Username: u0138016
                State: finished
       SubmitDateTime: 01-Mar-2023 17:36:48
        StartDateTime: 01-Mar-2023 17:37:22
      RunningDuration: 0 days 7h 6m 19s
           NumThreads: 2

      AutoAttachFiles: true
  Auto Attached Files: List files
        AttachedFiles: {}
    AutoAddClientPath: true
      AdditionalPaths: 27 paths

    Associated Tasks: 

       Number Pending: 0
       Number Running: 0
      Number Finished: 1
    Task ID of Errors: [1]
  Task ID of Warnings: []

 Task with properties: 

                   ID: 1
                State: finished
             Function: @parallel.internal.cluster.executeFunction
               Parent: Job 254
        StartDateTime: 01-Mar-2023 17:37:22
      RunningDuration: 0 days 7h 6m 18s

                Error: Not enough input arguments.
                       getHeelstrikeSimulation (line 38)
                       OCP_formulation (line 1120)
                       run_pred_sim (line 115)
             Warnings: none
````

**Software versions**
 - Windows 10
 - MATLAB 2021b
 - OpenSim 4.3
 - CasADi 3.5.5
 - Microsoft Visual Studio 15 2017 Win64
 - CMake 3.20.0-rc1

**Additional context**
/

**Comment by dgupta7** [comment]
I have made a pull request to add this change to master

**Comment by VDB-Bram** [comment]
In my simulations I still see a relative peak, though it's absolute value is still rather small. 
![image](https://user-images.githubusercontent.com/54840594/227244297-58fcdacb-0356-40d8-b940-783d2526e1b8.png)

**Comment by Lars-DHondt-KUL** [comment]
These peaks are between 100 and 1000 times lower than what we allow as constraint violation (1E-4). So this is fine.

**Comment by VDB-Bram** [comment]
Below some test results from FGC PredSims with 4 different gen scaled asymmetric models. It seems the bug is fixed.

![image](https://user-images.githubusercontent.com/54840594/227475363-a2b2f63b-7ca2-4971-ae4e-952da9a78561.png)
![image](https://user-images.githubusercontent.com/54840594/227474487-f9b8e952-816d-46ea-b3ec-1c9887ea274f.png)
![image](https://user-images.githubusercontent.com/54840594/227474779-fab0a143-06d0-4717-847e-e795e47affed.png)
![image](https://user-images.githubusercontent.com/54840594/227475007-280796df-4cbc-4c7d-b8d8-7cef745eac5f.png)

**Comment by VDB-Bram** [comment]
If you ran FullGaitCycle simulations before this bug was fixed, you can follow these steps to solve the issue.

1. Check the torques of the pelvis from your previous results. Sometimes this bug did not occur, so your results might be fine.
2. If you find T_ID torques on the pelvis greater than the constraints in your optimization problem, you should re-run the reconstruction. With the fixed code in `main.m`
    - since your previous settings will be read (all paths included), update the repo on your machine to be the fixed code or change branch.
    - have `S.subject.save_folder` pointing to the folder where your results are stored
    - set `S.post_process.result_filename` to the results you want to redo.
    - set `S.post_process.load_prev_opti_vars = 1;` 
    - set `S.post_process.rerun = 0; `

    - ⚠️**WARNING**: your original results will be overwritten, it is a good idea to make a backup.
