### ISSUE TITLE
Error using casadi external

### ISSUE THREAD

**Issue by alerocco7** [KULeuvenNeuromechanics/PredSim#97]
*Before submitting a bug report, read the error messages in MATLAB. Some errors are there to inform you about inconsistent inputs for certain settings.* 

**Describe the bug**
The simulation stop riight after creating casadi external.

**To Reproduce**
1. Which script did you run?
 Current master brunch
3. What settings did you use? Default settings
4. What kind of OpenSim model did you use? Link to generic model, attach specific model, or describe model (bodies, joints, coordinates) if it is confidential.
Scaled model from Dhondt_2seg

**Log file**
[simmetric_scaling_CP8_halfGait_v0_3_20230505T184235_log.txt](https://github.com/KULeuvenNeuromechanics/PredSim/files/11408524/simmetric_scaling_CP8_halfGait_v0_3_20230505T184235_log.txt)

**Software versions**
 - Windows 10
 - MATLAB 2022
 - OpenSim 4.4
 - CasADi 3.5.5
 - Microsoft Visual Studio 17 2022
 - CMake ...

[simmetric_scaling_CP8_halfGait_v0_3_20230505T184235_log.txt](https://github.com/KULeuvenNeuromechanics/PredSim/files/11408524/simmetric_scaling_CP8_halfGait_v0_3_20230505T184235_log.txt)

**Comment by VDB-Bram** [comment]
Error seems to be similar to what was reported here: https://github.com/casadi/casadi/issues/2909

Tested if the dll created with your account can be used by other user accounts on the same computer using the same Matlab installation. There were no issues.

After some debugging I narrowed it down to
* line 76 in C:\GBW_MyPrograms\casadi_3_5_5\+casadi\external.m: `[varargout{1:nargout}] = casadiMEX(779, varargin{:});`

Needs some further investigation.
