### ISSUE TITLE
some bounds need to be made symmetric

### ISSUE THREAD

**Issue by VDB-Bram** [KULeuvenNeuromechanics/PredSim#98]
*Before submitting a bug report, read the error messages in MATLAB. Some errors are there to inform you about inconsistent inputs for certain settings.* 

**Describe the bug**
The bounds of pelvis list and rotation and lumbar bending and rotation are not symmetric while they should be, I think.

**To Reproduce**
1. Which script did you run? main.m in commit 485db37
2. What settings did you use? default settings
3. What kind of OpenSim model did you use? Link to generic model, attach specific model, or describe model (bodies, joints, coordinates) if it is confidential. D'Hondt_2023_2seg

**Log file**
N/A

**Software versions**
 - Windows 10
 - MATLAB 2021b
 - OpenSim 4.3
 - CasADi 3.5.5
 - Microsoft Visual Studio 17 2022
 - CMake 3.22.0

**Additional context**
N/A

**Comment by Lars-DHondt-KUL** [comment]
Has been added to #89
