### ISSUE TITLE
Windows 11 compatibility not tested

### ISSUE THREAD

**Issue by VDB-Bram** [KULeuvenNeuromechanics/PredSim#99]

**Comment by VDB-Bram** [comment]
Great! Could you share your results?

**Comment by tombuurke** [comment]
Here you are (zip at the bottom):
![image](https://github.com/KULeuvenNeuromechanics/PredSim/assets/70269984/6d85cca1-48df-4169-bc2c-4019c5c3f253)
![image](https://github.com/KULeuvenNeuromechanics/PredSim/assets/70269984/3f736cac-970c-4543-95ee-ffb6f84e432c)
[Falisse_et_al_2022.zip](https://github.com/KULeuvenNeuromechanics/PredSim/files/11633475/Falisse_et_al_2022.zip)
